model_params:
  name: 'GAN'
  d_depth: 4
  g_depth: 4
  negative_slope: 0.2

exp_params:
  d_LR: 0.0002
  d_WD: 0.00001
  g_LR: 0.0002
  g_WD: 0.00001
  enable_distill_penalty: True
  batch_size: 100
  num_epochs: 20
  lmd: 0.0000001